image: maven:3.9.9-amazoncorretto-17-alpine

pipelines:
  default:
    - step:
        caches:
          - maven
        script:
          - mvn --version
          - mvn clean verify javadoc:jar --settings ./bin/settings.xml
  custom:
    perform-release:
      - variables:
          - name: releaseVersion
          - name: nextDevVersion
      - step:
          name: Perform release
          script:
            - mvn --version
            # Annoyingly there are no supported maven base images with JDK 17 and Git
            # Resorting to installing git here
            - apk add git
            - git --version
            - apk add gpg
            - gpg --version
            - mvn -B release:prepare -DreleaseVersion=${releaseVersion} -DdevelopmentVersion=${nextDevVersion} -DscmCommentPrefix="[skip ci]"
            - mvn -B release:perform -DscmCommentPrefix="[skip ci]"
