<?xml version="1.0" encoding="UTF-8"?>

<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.atlassian.pom</groupId>
        <artifactId>public-pom</artifactId>
        <version>4.0.18</version>
    </parent>

    <groupId>com.atlassian.oai</groupId>
    <artifactId>swagger-request-validator</artifactId>
    <version>0.0.1-SNAPSHOT</version>
    <packaging>pom</packaging>

    <description>
        Validation of request/responses against a Swagger/OpenAPI specification.

        Includes a standalone validator, as well as adapters for Pact and other mocking/http libraries.
    </description>

    <developers>
        <developer>
            <name>James Navin</name>
            <email>jnavin@atlassian.com</email>
            <organization>Atlassian</organization>
        </developer>
    </developers>

    <properties>
        <pact-jvm.version>3.2.6</pact-jvm.version>
        <junit.version>4.12</junit.version>
        <swagger-parser.version>1.0.19</swagger-parser.version>
        <json-schema-validator.version>2.2.6</json-schema-validator.version>
        <jdk.version>1.8</jdk.version>
        <mockito.version>1.10.19</mockito.version>
        <hamcrest.version>1.3</hamcrest.version>
        <slf4j.version>1.7.20</slf4j.version>
        <logback.version>1.0.13</logback.version>
        <rest-assured.version>2.9.0</rest-assured.version>
    </properties>

    <modules>
        <module>swagger-request-validator-core</module>
        <module>swagger-request-validator-pact</module>
        <module>swagger-request-validator-examples</module>
    </modules>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>com.atlassian.oai</groupId>
                <artifactId>swagger-request-validator-core</artifactId>
                <version>${version}</version>
            </dependency>
            <dependency>
                <groupId>com.atlassian.oai</groupId>
                <artifactId>swagger-request-validator-pact</artifactId>
                <version>${version}</version>
            </dependency>

            <dependency>
                <groupId>io.swagger</groupId>
                <artifactId>swagger-parser</artifactId>
                <version>${swagger-parser.version}</version>
            </dependency>
            <dependency>
                <groupId>com.github.fge</groupId>
                <artifactId>json-schema-validator</artifactId>
                <version>${json-schema-validator.version}</version>
            </dependency>
            <dependency>
                <groupId>au.com.dius</groupId>
                <artifactId>pact-jvm-model_2.11</artifactId>
                <version>${pact-jvm.version}</version>
            </dependency>
            <dependency>
                <groupId>junit</groupId>
                <artifactId>junit</artifactId>
                <version>${junit.version}</version>
            </dependency>
            <dependency>
                <groupId>au.com.dius</groupId>
                <artifactId>pact-jvm-consumer-junit_2.11</artifactId>
                <version>${pact-jvm.version}</version>
            </dependency>
            <dependency>
                <groupId>au.com.dius</groupId>
                <artifactId>pact-jvm-consumer_2.11</artifactId>
                <version>${pact-jvm.version}</version>
            </dependency>
            <dependency>
                <groupId>org.mockito</groupId>
                <artifactId>mockito-core</artifactId>
                <version>${mockito.version}</version>
            </dependency>
            <dependency>
                <groupId>org.hamcrest</groupId>
                <artifactId>hamcrest-library</artifactId>
                <version>${hamcrest.version}</version>
            </dependency>
            <dependency>
                <groupId>org.slf4j</groupId>
                <artifactId>slf4j-api</artifactId>
                <version>${slf4j.version}</version>
            </dependency>
            <dependency>
                <groupId>ch.qos.logback</groupId>
                <artifactId>logback-classic</artifactId>
                <version>${logback.version}</version>
            </dependency>
            <dependency>
                <groupId>com.jayway.restassured</groupId>
                <artifactId>rest-assured</artifactId>
                <version>${rest-assured.version}</version>
            </dependency>
        </dependencies>
    </dependencyManagement>

</project>