package com.atlassian.oai.validator.whitelist;

import com.atlassian.oai.validator.whitelist.rule.WhitelistRule;

import java.util.Objects;

public class NamedWhitelistRule {
    private final String name;
    private final WhitelistRule rule;

    @Override
    public String toString() {
        return name + " (" + rule + ")";
    }

    // The code below has been generated by Bob the Builder of Beans based on the class' fields.
    // Everything after this comment will be regenerated if you invoke Bob again.
    // If you don't know who Bob the Builder of Beans is, you can find him here: https://bitbucket.org/atlassian/bob

    NamedWhitelistRule(String name, WhitelistRule rule) {
        this.name = Objects.requireNonNull(name);
        this.rule = Objects.requireNonNull(rule);
    }

    public String getName() {
        return name;
    }

    public WhitelistRule getRule() {
        return rule;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) { return true; }
        if (o == null || getClass() != o.getClass()) { return false; }

        NamedWhitelistRule that = (NamedWhitelistRule) o;

        return Objects.equals(this.getName(), that.getName()) &&
                Objects.equals(this.getRule(), that.getRule());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getName(), getRule());
    }
}
