package com.atlassian.oai.validator.whitelist;

import com.atlassian.oai.validator.model.ApiOperation;
import com.atlassian.oai.validator.model.Request;
import com.atlassian.oai.validator.model.Response;
import com.atlassian.oai.validator.report.ValidationReport;
import com.atlassian.oai.validator.whitelist.rule.WhitelistRule;
import com.google.common.base.MoreObjects;
import com.google.common.collect.ImmutableList;

import java.util.Collections;
import java.util.List;
import java.util.Objects;
import java.util.Optional;

public final class ValidationWhitelist {

    private final List<WhitelistRule> rules;

    public static ValidationWhitelist empty() {
        return new ValidationWhitelist(Collections.emptyList());
    }

    public ValidationWhitelist withRule(WhitelistRule rule) {
        return new ValidationWhitelist(
                ImmutableList.<WhitelistRule>builder().addAll(rules).add(rule).build());
    }

    public boolean isWhitelisted(ValidationReport.Message message, ApiOperation operation, Request request, Response response) {
        return rules.stream().anyMatch(rule -> rule.matches(message, operation, request, response));
    }

    public Optional<WhitelistRule> whitelistedBy(ValidationReport.Message message, ApiOperation operation, Request request, Response response) {
        return rules.stream()
                .filter(rule -> rule.matches(message, operation, request, response))
                .findFirst();
    }

// The code below has been generated by Bob the Builder of Beans based on the class' fields.
// Everything after this comment will be regenerated if you invoke Bob again.
// If you don't know who Bob the Builder of Beans is, you can find him here: https://bitbucket.org/atlassian/bob

    public ValidationWhitelist(Iterable<WhitelistRule> rules) {
        this.rules = ImmutableList.copyOf(rules);
    }

    public List<WhitelistRule> getRules() {
        return rules;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) { return true; }
        if (o == null || getClass() != o.getClass()) { return false; }

        ValidationWhitelist that = (ValidationWhitelist) o;

        return Objects.equals(this.getRules(), that.getRules());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getRules());
    }

    @Override
    public String toString() {
        return MoreObjects.toStringHelper(this)
                .add("rules", getRules())
                .toString();
    }
}
