<?xml version="1.0" encoding="UTF-8"?>

<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>com.atlassian.oai</groupId>
        <artifactId>openapi-request-validator</artifactId>
        <version>3.0.0-SNAPSHOT</version>
        <relativePath>../pom.xml</relativePath>
    </parent>

    <artifactId>openapi-request-validator-examples</artifactId>

    <name>OpenAPI Request Validator - Examples</name>
    <description>
        Example usages of the Swagger Request Validator and its various integrations and adapters.
    </description>

    <dependencies>
        <dependency>
            <groupId>com.atlassian.oai</groupId>
            <artifactId>openapi-request-validator-core</artifactId>
        </dependency>
        <dependency>
            <groupId>com.atlassian.oai</groupId>
            <artifactId>openapi-request-validator-pact</artifactId>
        </dependency>
        <dependency>
            <groupId>com.atlassian.oai</groupId>
            <artifactId>openapi-request-validator-restassured</artifactId>
        </dependency>
        <dependency>
            <groupId>com.atlassian.oai</groupId>
            <artifactId>openapi-request-validator-mockmvc</artifactId>
        </dependency>
        <dependency>
            <groupId>com.atlassian.oai</groupId>
            <artifactId>openapi-request-validator-spring-web-client</artifactId>
        </dependency>

        <dependency>
            <groupId>ch.qos.logback</groupId>
            <artifactId>logback-classic</artifactId>
        </dependency>

        <dependency>
            <groupId>io.rest-assured</groupId>
            <artifactId>rest-assured</artifactId>
            <scope>test</scope>
        </dependency>

        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>au.com.dius.pact.consumer</groupId>
            <artifactId>junit5</artifactId>
            <version>${pact-jvm.version}</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>au.com.dius.pact</groupId>
            <artifactId>consumer</artifactId>
        </dependency>
        <dependency>
            <groupId>au.com.dius.pact</groupId>
            <artifactId>provider</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework</groupId>
            <artifactId>spring-web</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework</groupId>
            <artifactId>spring-webmvc</artifactId>
        </dependency>
        <dependency>
            <groupId>org.wiremock</groupId>
            <artifactId>wiremock</artifactId>
            <scope>test</scope>
        </dependency>
    </dependencies>

</project>
